# Generated by Django 4.2.5 on 2023-09-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="course", old_name="price", new_name="fees",),
        migrations.RenameField(
            model_name="course", old_name="seats_available", new_name="no_of_seats",
        ),
    ]
